// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int timesToRepeat = Integer.parseInt(args[0]);
		int countBiggerThanHalf = 0;
		int countLessThanOrEqualToHalf = 0;
		for (int i = 0; i < timesToRepeat; i++) {
			double r = Math.random();
			if (r > 0.5) {
				countBiggerThanHalf++;
			} else {
				countLessThanOrEqualToHalf++;
			}
		}
	}
}
